#!/bin/sh
# N. Ratnikova Sep, 11, 2015
# NewNodesSQL
#  - takes a comma separated list of new node names as first argument
#  - assigns next ID based on the current max node ID
#  - relies on OracleConnectId and proper DBPARAM for accessing as DB admin,
#    documented elsewhere (see PhEDEx or SpaceMon internal docs)
#  - creates sql script in temporary directory under /tmp, which can be 
#    inspected and executed manually. 
#####
# Borrow  secure connection method from PhEDEx :  

secure_connect=$(OracleConnectId -db $DBPARAM)

tmpwork=`mktemp -d` 
sql_script=${tmpwork}/newnodes.sql
touch $sql_script
echo "Constructing SQL query in $sql_script ... "

function cleanup {
	rm -r $tmpwork
	exit $1
}
trap cleanup SIGHUP SIGINT SIGTERM

max_id=`echo "select max(id) from t_adm_node;" | sqlplus $secure_connect | grep -A 1 '^-------' | tail -1 | awk '{print $1}'`

echo " Current max ID : " $max_id
let next_id=max_id+1
for n in `echo $1 | tr "," " " ` ; do 
  # Basic sanity check for node names:
  if [ `echo $n | grep '^T' `sfx != ${n}sfx ]
  then
    echo "Node name does not pass the sanity check: $n"
    continue
  fi
  # insert into t_adm_node (ID, NAME) VALUES ( 169, 'T2_MY_UPM_BIRUNI');
  echo "insert into t_adm_node (ID, NAME) VALUES ("$next_id", '"$n"');" >> $sql_script
  echo "Added: $n "
  let next_id=next_id+1
done
echo "quit;" >>  $sql_script
echo
echo "Please inspect the script:"
echo "   $sql_script" 
echo "and if everything is correct, execute it as follows:"
echo "    sqlplus \$(OracleConnectId -db \$DBPARAM) @"$sql_script
echo